.TH "lib Directory Reference" 3 "Version medkit" "MedKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBnet\fP"
.br
.ti -1c
.RI "directory \fBsrc\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBauth\&.hpp\fP"
.br
.ti -1c
.RI "file \fBcommon\&.hpp\fP"
.br
.ti -1c
.RI "file \fBconfig\&.hpp\fP"
.br
.ti -1c
.RI "file \fBMedKit\&.hpp\fP"
.br
.ti -1c
.RI "file \fBsteady\&.hpp\fP"
.br
.in -1c
