.TH "lib/auth.hpp" 3 "Version medkit" "MedKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/auth.hpp
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBmedkit\fP"
.br
.ti -1c
.RI "namespace \fBmedkit::auth\fP"
.br
.RI "
.br
 The Network Packets sent during the authentication phase of the program "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MedKit from the source code\&.
