.TH "lib/config.hpp" 3 "Version medkit" "MedKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/config.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <stdint\&.h>\fP
.br
\fR#include <stddef\&.h>\fP
.br
\fR#include 'common\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBmedkit::StringTable< size_type >\fP"
.br
.RI "limited to 2^(sizeof(size_type) characters allows lookups to be faster because length is a heuristic "
.ti -1c
.RI "struct \fBmedkit::ConfigurationProfileRequest< size_type >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBmedkit\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MedKit from the source code\&.
