.TH "lib/src/example.cpp" 3 "Version medkit" "MedKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/src/example.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <medkit/net/Network\&.hpp>\fP
.br
\fR#include <medkit/steady\&.hpp>\fP
.br
\fR#include <sys/socket\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBSocketConnectionInfo\fP"
.br
.ti -1c
.RI "struct \fBmedkit::NetworkInterfaceTrait< SocketHandle, SocketConnectionInfo >\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int \fBSocketHandle\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBResult\fP "
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef int \fBSocketHandle\fP"

.PP
Definition at line \fB11\fP of file \fBexample\&.cpp\fP\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBmedkit::Result\fP"

.PP
Definition at line \fB4\fP of file \fBMedKit\&.hpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Definition at line \fB34\fP of file \fBexample\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MedKit from the source code\&.
