.TH "medkit::steady::Request::Content::Reconfigure" 3 "Version medkit" "MedKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
medkit::steady::Request::Content::Reconfigure
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <steady\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBmust_reauthenticate\fP"
.br
.ti -1c
.RI "uint32_t \fBresv\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB54\fP of file \fBsteady\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint32_t medkit::steady::Request::Content::Reconfigure::must_reauthenticate"

.PP
Definition at line \fB56\fP of file \fBsteady\&.hpp\fP\&.
.SS "uint32_t medkit::steady::Request::Content::Reconfigure::resv"

.PP
Definition at line \fB57\fP of file \fBsteady\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MedKit from the source code\&.
