.TH "medkit::steady::Response::Content::Param" 3 "Version medkit" "MedKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
medkit::steady::Response::Content::Param
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <steady\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBparam_value\fP"
.br
.ti -1c
.RI "uint32_t \fBresv\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB109\fP of file \fBsteady\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint32_t medkit::steady::Response::Content::Param::param_value"

.PP
Definition at line \fB110\fP of file \fBsteady\&.hpp\fP\&.
.SS "uint32_t medkit::steady::Response::Content::Param::resv"

.PP
Definition at line \fB111\fP of file \fBsteady\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MedKit from the source code\&.
