.TH "lib/MedKit.hpp" 3 "Version medkit" "MedKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/MedKit.hpp
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBmedkit\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBmedkit::Result\fP { \fBmedkit::Success\fP, \fBmedkit::NetworkLost\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MedKit from the source code\&.
