.TH "medkit::steady::Request::Content::Reauthenticate" 3 "Version medkit" "MedKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
medkit::steady::Request::Content::Reauthenticate
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <steady\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBreceive_new_key\fP:32"
.br
.ti -1c
.RI "uint32_t \fBresv\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB46\fP of file \fBsteady\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool medkit::steady::Request::Content::Reauthenticate::receive_new_key"

.PP
Definition at line \fB50\fP of file \fBsteady\&.hpp\fP\&.
.SS "uint32_t medkit::steady::Request::Content::Reauthenticate::resv"

.PP
Definition at line \fB51\fP of file \fBsteady\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MedKit from the source code\&.
