.TH "medkit::steady::Response::Content" 3 "Version medkit" "MedKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
medkit::steady::Response::Content
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <steady\&.hpp>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBJobData\fP"
.br
.ti -1c
.RI "struct \fBParam\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBraw\fP"
.br
.ti -1c
.RI "struct \fBmedkit::steady::Response::Content::Param\fP \fBparam\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB99\fP of file \fBsteady\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "struct \fBmedkit::steady::Response::Content::Param\fP medkit::steady::Response::Content::param"

.SS "uint64_t medkit::steady::Response::Content::raw"

.PP
Definition at line \fB100\fP of file \fBsteady\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MedKit from the source code\&.
