.TH "medkit::steady::Response::Content::JobData" 3 "Version medkit" "MedKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
medkit::steady::Response::Content::JobData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <steady\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBStatus\fP { \fBKILLED\fP, \fBDONE\fP, \fBRUNNING\fP }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "enum \fBmedkit::steady::Response::Content::JobData::Status\fP \fBstatus\fP"
.br
.ti -1c
.RI "uint32_t \fBexit_code\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB101\fP of file \fBsteady\&.hpp\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBmedkit::steady::Response::Content::JobData::Status\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIKILLED \fP
.TP
\f(BIDONE \fP
.TP
\f(BIRUNNING \fP
.PP
Definition at line \fB102\fP of file \fBsteady\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint32_t medkit::steady::Response::Content::JobData::exit_code"

.PP
Definition at line \fB107\fP of file \fBsteady\&.hpp\fP\&.
.SS "enum \fBmedkit::steady::Response::Content::JobData::Status\fP medkit::steady::Response::Content::JobData::status"


.SH "Author"
.PP 
Generated automatically by Doxygen for MedKit from the source code\&.
