.TH "medkit::steady::Request::Content::GetRequestStatus" 3 "Version medkit" "MedKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
medkit::steady::Request::Content::GetRequestStatus
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <steady\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBrequest_number\fP"
.br
.ti -1c
.RI "uint32_t \fBresv\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB72\fP of file \fBsteady\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint32_t medkit::steady::Request::Content::GetRequestStatus::request_number"

.PP
Definition at line \fB73\fP of file \fBsteady\&.hpp\fP\&.
.SS "uint32_t medkit::steady::Request::Content::GetRequestStatus::resv"

.PP
Definition at line \fB74\fP of file \fBsteady\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MedKit from the source code\&.
