.TH "medkit::steady::Request::Content" 3 "Version medkit" "MedKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
medkit::steady::Request::Content
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <steady\&.hpp>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBGetRequestStatus\fP"
.br
.ti -1c
.RI "struct \fBReadParam\fP"
.br
.ti -1c
.RI "struct \fBReauthenticate\fP"
.br
.ti -1c
.RI "struct \fBReconfigure\fP"
.br
.ti -1c
.RI "struct \fBRequestSensorHook\fP"
.br
.ti -1c
.RI "struct \fBSetParam\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBraw\fP"
.br
.ti -1c
.RI "struct \fBmedkit::steady::Request::Content::Reauthenticate\fP \fBreauthenticate\fP"
.br
.ti -1c
.RI "struct \fBmedkit::steady::Request::Content::Reconfigure\fP \fBreconfigure\fP"
.br
.ti -1c
.RI "struct \fBmedkit::steady::Request::Content::SetParam\fP \fBset_param\fP"
.br
.ti -1c
.RI "struct \fBmedkit::steady::Request::Content::ReadParam\fP \fBread_param\fP"
.br
.ti -1c
.RI "struct \fBmedkit::steady::Request::Content::GetRequestStatus\fP \fBget_request_status\fP"
.br
.ti -1c
.RI "struct \fBmedkit::steady::Request::Content::RequestSensorHook\fP \fBrequestsensorhook\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB43\fP of file \fBsteady\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "struct \fBmedkit::steady::Request::Content::GetRequestStatus\fP medkit::steady::Request::Content::get_request_status"

.SS "uint64_t medkit::steady::Request::Content::raw"

.PP
Definition at line \fB44\fP of file \fBsteady\&.hpp\fP\&.
.SS "struct \fBmedkit::steady::Request::Content::ReadParam\fP medkit::steady::Request::Content::read_param"

.SS "struct \fBmedkit::steady::Request::Content::Reauthenticate\fP medkit::steady::Request::Content::reauthenticate"

.SS "struct \fBmedkit::steady::Request::Content::Reconfigure\fP medkit::steady::Request::Content::reconfigure"

.SS "struct \fBmedkit::steady::Request::Content::RequestSensorHook\fP medkit::steady::Request::Content::requestsensorhook"

.SS "struct \fBmedkit::steady::Request::Content::SetParam\fP medkit::steady::Request::Content::set_param"


.SH "Author"
.PP 
Generated automatically by Doxygen for MedKit from the source code\&.
