.TH "medkit::steady::Request::Content::ReadParam" 3 "Version medkit" "MedKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
medkit::steady::Request::Content::ReadParam
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <steady\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBparam_handle\fP"
.br
.ti -1c
.RI "uint32_t \fBparam_value\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB66\fP of file \fBsteady\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint32_t medkit::steady::Request::Content::ReadParam::param_handle"

.PP
Definition at line \fB68\fP of file \fBsteady\&.hpp\fP\&.
.SS "uint32_t medkit::steady::Request::Content::ReadParam::param_value"

.PP
Definition at line \fB69\fP of file \fBsteady\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MedKit from the source code\&.
