.TH "medkit::ConfigurationProfileRequest< size_type >" 3 "Version medkit" "MedKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
medkit::ConfigurationProfileRequest< size_type >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <config\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBstring_table\fP = \fBStringTable\fP<size_type>"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "uint8_t * \fBdata\fP (size_t &total_size)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBRole\fP \fBrole\fP: 8"
.br
.ti -1c
.RI "\fBstring_table\fP \fBavailable_feature_list\fP"
.br
.ti -1c
.RI "\fBstring_table\fP \fBrequired_feature_list\fP"
.br
.ti -1c
.RI "\fBstring_table\fP \fBparameter_list\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename size_type>
.br
struct medkit::ConfigurationProfileRequest< size_type >"
.PP
Definition at line \fB42\fP of file \fBconfig\&.hpp\fP\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename size_type> using \fBmedkit::ConfigurationProfileRequest\fP< size_type >::string_table = \fBStringTable\fP<size_type>"

.PP
Definition at line \fB46\fP of file \fBconfig\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename size_type> uint8_t * \fBmedkit::ConfigurationProfileRequest\fP< size_type >::data (size_t & total_size)\fR [inline]\fP"

.PP
Definition at line \fB52\fP of file \fBconfig\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename size_type> \fBstring_table\fP \fBmedkit::ConfigurationProfileRequest\fP< size_type >::available_feature_list"

.PP
Definition at line \fB47\fP of file \fBconfig\&.hpp\fP\&.
.SS "template<typename size_type> \fBstring_table\fP \fBmedkit::ConfigurationProfileRequest\fP< size_type >::parameter_list"

.PP
Definition at line \fB49\fP of file \fBconfig\&.hpp\fP\&.
.SS "template<typename size_type> \fBstring_table\fP \fBmedkit::ConfigurationProfileRequest\fP< size_type >::required_feature_list"

.PP
Definition at line \fB48\fP of file \fBconfig\&.hpp\fP\&.
.SS "template<typename size_type> \fBRole\fP \fBmedkit::ConfigurationProfileRequest\fP< size_type >::role"

.PP
Definition at line \fB45\fP of file \fBconfig\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MedKit from the source code\&.
