.TH "medkit::steady" 3 "Version medkit" "MedKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
medkit::steady
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBRequest\fP"
.br
.ti -1c
.RI "struct \fBResponse\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MedKit from the source code\&.
