.TH "medkit::steady::Request::Content::RequestSensorHook" 3 "Version medkit" "MedKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
medkit::steady::Request::Content::RequestSensorHook
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <steady\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBThreshold\fP { \fBAbove\fP = 0x01, \fBBelow\fP = 0x02, \fBTrigger\fP = Above | Below }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBparam_handle\fP:30"
.br
.ti -1c
.RI "uint32_t \fBparam_value\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB77\fP of file \fBsteady\&.hpp\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBmedkit::steady::Request::Content::RequestSensorHook::Threshold\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIAbove \fP
.TP
\f(BIBelow \fP
.TP
\f(BITrigger \fP
.PP
Definition at line \fB78\fP of file \fBsteady\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint32_t medkit::steady::Request::Content::RequestSensorHook::param_handle"

.PP
Definition at line \fB83\fP of file \fBsteady\&.hpp\fP\&.
.SS "uint32_t medkit::steady::Request::Content::RequestSensorHook::param_value"

.PP
Definition at line \fB84\fP of file \fBsteady\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MedKit from the source code\&.
