.TH "SocketConnectionInfo" 3 "Version medkit" "MedKit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SocketConnectionInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const struct sockaddr * \fBaddr\fP"
.br
.ti -1c
.RI "socklen_t \fBaddrlen\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBexample\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const struct sockaddr* SocketConnectionInfo::addr"

.PP
Definition at line \fB7\fP of file \fBexample\&.cpp\fP\&.
.SS "socklen_t SocketConnectionInfo::addrlen"

.PP
Definition at line \fB8\fP of file \fBexample\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MedKit from the source code\&.
